"""Portable reference401 interior target from any Wout, checked against the public starter.

The maintainer's qualified field archives are local-only. This rebuilds the same
s=0.25/0.5/0.75 64x64 archive arrays from a Wout (for example one regenerated by
vmecpp from the committed input), using the sampler retired at fb7eda7
(qi_field_grid.sample), and accepts them only if the boundary matches the input
and the public starter's 64 interior samples are reproduced.
"""

import hashlib
from pathlib import Path

import numpy as np

STARTER = "examples/clear-coil-samples-v1/case.json"
SURFACES = (0.25, 0.5, 0.75)


def need(condition, message):
    if not condition:
        raise ValueError(message)


def sample(data, surface, resolution=64):
    """VMEC contravariant field on one interpolated surface, one field period in phi."""
    def read(key):
        value = np.ma.asarray(data[key][...], dtype=float).filled(np.nan)
        need(np.isfinite(value).all(), f"nonfinite Wout value: {key}")
        return value

    ns, nfp = int(read("ns").item()), int(read("nfp").item())
    need(ns >= 3 and nfp == 2 and read("lasym__logical__").item() == 0,
         "symmetric nfp2 Wout required")
    full = np.linspace(0, 1, ns)
    half = (full[:-1] + full[1:]) / 2
    need(half[0] <= surface <= half[-1], "interior half-mesh surface required")

    def radial(key, half_mesh=True):
        grid, values = (half, read(key)[1:]) if half_mesh else (full, read(key))
        return np.array([np.interp(surface, grid, v) for v in values.T])

    m, n, mn, nn = (read(k) for k in ("xm", "xn", "xm_nyq", "xn_nyq"))
    phi, theta = np.meshgrid(2*np.pi*np.arange(resolution)/(resolution*nfp),
                             2*np.pi*np.arange(resolution)/resolution, indexing="ij")
    phase = m[:, None]*theta.ravel() - n[:, None]*phi.ravel()
    c, s = np.cos(phase), np.sin(phase)

    def project(coefficients, basis=c):
        return (coefficients @ basis).reshape(theta.shape)

    r, z = radial("rmnc", False), radial("zmns", False)
    radius, height = project(r), project(z, s)
    rt, rp, zt, zp = project(-m*r, s), project(n*r, s), project(m*z), project(-n*z)
    nyquist = np.cos(mn[:, None]*theta.ravel() - nn[:, None]*phi.ravel())
    bt, bp = project(radial("bsupumnc"), nyquist), project(radial("bsupvmnc"), nyquist)
    et = np.stack((rt*np.cos(phi), rt*np.sin(phi), zt), axis=-1)
    ep = np.stack((rp*np.cos(phi) - radius*np.sin(phi), rp*np.sin(phi) + radius*np.cos(phi), zp),
                  axis=-1)
    return dict(phi=phi, theta=theta, radius=radius, height=height, bt=bt, bp=bp, et=et, ep=ep,
                native=bt[..., None]*et + bp[..., None]*ep)


def archives(wout, target_input):
    """Three qualified-format 64x64 archives after boundary and edge-flux identity checks."""
    import netCDF4

    path = Path(wout)
    with path.open("rb") as stream:
        sha256 = hashlib.file_digest(stream, "sha256").hexdigest()
    with netCDF4.Dataset(path) as data:
        need(int(data["ns"][...]) == 401 and abs(float(data["phi"][-1]) - target_input["phiedge"])
             <= 1e-14, "401-surface Wout with the input's edge flux required")
        m, n = np.asarray(data["xm"][:]), np.asarray(data["xn"][:]) / 2
        for key, wkey in (("rbc", "rmnc"), ("zbs", "zmns")):
            intended = {(row["m"], row["n"]): row["value"] for row in target_input[key]}
            actual = {(int(a), int(b)): float(v) for a, b, v in
                      zip(m, n, data[wkey][-1], strict=True)}
            error = max(abs(intended.get(k, 0) - actual.get(k, 0))
                        for k in intended.keys() | actual.keys())
            need(error <= 1e-12, f"Wout boundary differs from input {key}: {error}")
        rows = [dict(s=s, n=64, arrays=sample(data, s)) for s in SURFACES]
    return rows, sha256


def starter_errors(target32, starter):
    """Relative max error of the 64 published interior samples (points and target B)."""
    inner = starter["groups"]["inner"]
    index = inner["indices"]
    errors = {}
    for key, published in (("inner_points", "points_m"), ("inner_target", "target_B_T")):
        expected = np.asarray(inner[published], dtype=float)
        errors[key] = float(np.max(abs(target32[key][index] - expected)) / np.max(abs(expected)))
    return errors
