"""Small fixed reference calibration; exploratory, not Step 4 acceptance."""

import argparse
import json
import os
import shutil
import time
from pathlib import Path

import numpy as np

from fusion_baselines.boundary_control_metrics import boundary_metrics
from fusion_baselines.provenance import git_state, sha256_file

ROOT = Path(__file__).resolve().parents[1]
QUASR = "external/simsopt/tests/test_files/serial0000952.json"
LPQA = "external/stellcoilbench/submissions/LandremanPaul2021_QA/auto/2026-02-17_083339_92598"
SURFACE = "external/stellcoilbench/plasma_surfaces/input.LandremanPaul2021_QA"
INPUTS = {
    QUASR: "8bf9b7a83ebf7b7ff20275b857937f4da91672ba9012c51ea481dbb5eb730934",
    SURFACE: "4c6ba4bc391a69b5b6a5e84ff82df9b0ce92e20c42f2a47f89a9283fd5bc3458",
    LPQA + "/order_8/biot_savart_optimized.json":
        "40c3abd2c172fdfc94be6a2b5de05ef2e29c3f37c8b4fbd04c6fdb47eef69b4a",
    LPQA + "/results.json":
        "48933af3cf40d3690b1a12b9fe3c14deae41eff4eb983c943f815010cbe5f968",
}
SCHEDULE = ((21, 160, 0.), (42, 160, 0.), (42, 320, 0.),
            (84, 320, 0.), (84, 640, 0.), (84, 640, .5))


def reference(path):
    return dict(path=str(path.resolve()), sha256=sha256_file(path), bytes=path.stat().st_size)


def save_json(path, value):
    with path.open("x", encoding="utf-8") as stream:
        stream.write(json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n")
        stream.flush()
        os.fsync(stream.fileno())


def clone_coils(original, base_count, nodes):
    from audit_coil_geometry import curve_points
    from simsopt.field import Current, coils_via_symmetries
    from simsopt.geo import CurveXYZFourier

    curves = []
    for coil in original[:base_count]:
        if hasattr(coil.curve, "rotmat"):
            raise ValueError("direct base curves required")
        curve = CurveXYZFourier(nodes, coil.curve.order)
        names = list(coil.curve.local_full_dof_names)
        if names != list(curve.local_full_dof_names):
            raise ValueError("named Fourier coefficient mapping differs")
        curve.local_full_x = coil.curve.local_full_x.copy()
        curves.append(curve)
    regularizations = ([float(c.regularization) for c in original[:base_count]]
                       if hasattr(original[0], "regularization") else None)
    copied = coils_via_symmetries(
        curves, [Current(c.current.get_value()) for c in original[:base_count]],
        2, True, regularizations=regularizations,
    )
    if len(copied) != len(original):
        raise ValueError("physical coil count changed")
    t = np.arange(257) / 257
    errors = []
    for before, after in zip(original, copied, strict=True):
        if before.current.get_value() != after.current.get_value():
            raise ValueError("physical current changed")
        if getattr(before, "regularization", None) != getattr(after, "regularization", None):
            raise ValueError("self-field regularization metadata changed")
        a, b = curve_points(before.curve, t), curve_points(after.curve, t)
        errors.append(float(np.max(np.abs(a-b)) / max(1., np.max(np.abs(a)))))
    if max(errors) > 1e-12:
        raise ValueError("coil position identity failed")
    return copied, max(errors)


def surface_grid(source, n, shift, half_period=False):
    from simsopt.geo import SurfaceRZFourier, SurfaceXYZTensorFourier

    if isinstance(source, Path):
        if half_period:
            return SurfaceRZFourier.from_vmec_input(
                str(source), range="half period", nphi=n, ntheta=n)
        return SurfaceRZFourier.from_vmec_input(
            str(source), quadpoints_phi=(np.arange(n)+shift)/(n*2),
            quadpoints_theta=(np.arange(n)+shift)/n)
    surface = SurfaceXYZTensorFourier(
        nfp=2, stellsym=True, mpol=source.mpol, ntor=source.ntor,
        clamped_dims=[False, False, False],
        quadpoints_phi=(np.arange(n)+shift)/(n*2),
        quadpoints_theta=(np.arange(n)+shift)/n,
    )
    # Old QUASR DOF containers have generic x0/x1 labels. Bind actual physical
    # tensor slots, whose names are generated by the native surface definition.
    if (source.clamped_dims != [False, False, False]
            or surface._make_names() != source._make_names()
            or not np.array_equal(source.get_dofs(), source.local_full_x)):
        raise ValueError("physical tensor surface mapping differs")
    physical = dict(zip(source._make_names(), source.get_dofs(), strict=True))
    surface.local_full_x = np.array([physical[name] for name in surface.local_full_dof_names])
    for component in ("xcs", "ycs", "zcs"):
        if not np.array_equal(getattr(surface, component), getattr(source, component)):
            raise ValueError("physical surface tensor changed")
    return surface


def independent_tangents(curve, parameter):
    from audit_coil_geometry import base_fourier

    from fusion_baselines.curvature_bounds import derivatives

    if hasattr(curve, "rotmat"):
        return independent_tangents(curve.curve, parameter) @ np.asarray(curve.rotmat)
    return derivatives(base_fourier(curve)[0], parameter)[0]


def run(output):
    started = time.monotonic()
    if output.exists():
        raise FileExistsError("fresh exploratory output required")
    if shutil.disk_usage(ROOT).free < 3 * 1024**3:
        raise RuntimeError("3 GiB starting reserve required")
    output.mkdir(parents=True)

    def guard():
        if time.monotonic() - started > 180:
            raise TimeoutError("180 s exploratory ceiling")
        if shutil.disk_usage(output).free < 2 * 1024**3:
            raise RuntimeError("2 GiB live reserve required")
        if sum(p.stat().st_size for p in output.rglob("*") if p.is_file()) > 64 * 1024**2:
            raise RuntimeError("64 MiB output ceiling")

    import simsopt
    import simsoptpp
    from audit_coil_geometry import curve_points
    from simsopt import load
    from simsopt.field import BiotSavart

    from fusion_baselines.filament_field import filament_field

    bound_paths = [ROOT / p for p in INPUTS]
    for name, expected in INPUTS.items():
        if sha256_file(ROOT / name) != expected:
            raise ValueError(f"fixed input identity changed: {name}")
    bound_paths.extend(ROOT / p for p in (
        LPQA + "/case.yaml", "scripts/explore_boundary_controls.py",
        "src/fusion_baselines/boundary_control_metrics.py",
        "src/fusion_baselines/filament_field.py", "scripts/audit_coil_geometry.py",
        "src/fusion_baselines/curvature_bounds.py",
    ))
    native_root = Path(simsopt.__file__).parent
    bound_paths.extend(native_root / p for p in (
        "field/biotsavart.py", "field/coil.py", "geo/curvexyzfourier.py",
        "geo/surfacexyztensorfourier.py", "geo/surfacerzfourier.py",
        "objectives/fluxobjective.py",
    ))
    bound_paths.append(Path(simsoptpp.__file__))
    sources = [reference(p) for p in bound_paths]
    report = dict(
        schema="exploratory-boundary-controls-v1", repository=git_state(ROOT),
        simsopt_version=simsopt.__version__, sources=sources, rows=[],
        acceptance=False, pressure=False, interior_target=False,
        inputs_unscaled=True, native_block_size=128, crosscheck_points=64,
        schedule=[list(x) for x in SCHEDULE],
    )
    save_json(output / "inputs.json", report)
    surfaces, quasr_coils = load(str(ROOT / QUASR))
    if len(surfaces) != 1 or surfaces[0].nfp != 2 or not surfaces[0].stellsym:
        raise ValueError("unexpected QUASR target")
    lpqa_field = load(str(ROOT / LPQA / "order_8/biot_savart_optimized.json"))
    for label, source, original, count in (
        ("quasr-952", surfaces[0], quasr_coils, 1),
        ("lpqa-92598", ROOT / SURFACE, lpqa_field.coils, 4),
    ):
        rows = [(*s, False) for s in SCHEDULE]
        if label == "lpqa-92598":
            rows.append((32, 256, 0., True))
        for number, (n, nodes, shift, half_period) in enumerate(rows):
            guard()
            coils, position_error = clone_coils(original, count, nodes)
            surface = surface_grid(source, n, shift, half_period)
            points, normals = surface.gamma().copy(), surface.normal().copy()
            field = BiotSavart(coils)
            flat, blocks = points.reshape(-1, 3), []
            for offset in range(0, len(flat), 128):
                guard()
                field.set_points(np.ascontiguousarray(flat[offset:offset+128]))
                blocks.append(field.B().copy())
            B = np.concatenate(blocks).reshape(points.shape)
            metrics = boundary_metrics(B, normals)
            t = np.arange(nodes) / nodes
            positions = np.array([curve_points(c.curve, t) for c in coils])
            tangents = np.array([independent_tangents(c.curve, t) for c in coils])
            currents = np.array([c.current.get_value() for c in coils])
            indices = np.linspace(0, len(flat)-1, 64, dtype=int)
            own = filament_field(flat[indices], positions, tangents, currents)
            native = B.reshape(-1, 3)[indices]
            error = float(np.max(np.linalg.norm(own-native, axis=1)
                                 / np.maximum(1., np.linalg.norm(native, axis=1))))
            flux_checks = {}
            for definition, key in (("quadratic flux", "raw_quadratic_flux"),
                                    ("local", "local_flux"),
                                    ("normalized", "normalized_global_flux")):
                value = float(simsoptpp.integral_BdotN(
                    np.ascontiguousarray(B), np.zeros((n, n)),
                    np.ascontiguousarray(normals), definition))
                flux_checks[definition] = dict(native=value, passes=bool(
                    np.isclose(value, metrics[key], rtol=1e-11, atol=1e-15)))
            stem = f"{label}-{number}"
            array_path = output / (stem + ".npz")
            with array_path.open("xb") as stream:
                np.savez_compressed(stream, points=points, normals=normals, B=B,
                                    indices=indices, independent=own, positions=positions,
                                    tangents=tangents, currents=currents)
            row = dict(case=label, n=n, nodes=nodes, shift=shift, half_period=half_period,
                       metrics=metrics, position_error=position_error,
                       independent_B_error=error, flux_checks=flux_checks,
                       arrays=reference(array_path))
            row["checks_pass"] = bool(error <= 1e-12 and all(
                v["passes"] for v in flux_checks.values()))
            save_json(output / (stem + ".json"), row)
            report["rows"].append(row)
            print(json.dumps(dict(case=label, grid=n, nodes=nodes, shift=shift,
                                  rms=metrics["normal_rms"], checks=row["checks_pass"])),
                  flush=True)
            if not row["checks_pass"]:
                raise ValueError("boundary calibration numerical check failed")
    guard()
    if sources != [reference(p) for p in bound_paths]:
        raise ValueError("input/evaluator changed during exploration")
    report.update(completed=True, elapsed_s=time.monotonic()-started)
    save_json(output / "result.json", report)
    print(json.dumps(reference(output / "result.json")), flush=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    run(parser.parse_args().output.resolve())
